theme: jekyll-theme-cayman
title: FairML
description: This is a collection of papers and other resources related to fairness in machine learning.
plugins:
  - jekyll-seo-tag
google_analytics: UA-111279954-1
timezone: America/Chicago
